### ISSUE TITLE
Run alongside other containers

### ISSUE THREAD

**Issue by Drime** [dciancu/unifi-protect-unvr-docker-arm64#36]
Thanks for this amazing project! I'm trying to run a protect container next to some other containers including unify-controller, thus `network_mode: host` cannot be used. Has anybody been able to run the container on e.g. a macvlan? Seems to work but protect keeps reporting it lacks internet access, devices are also not able to find protect. 

Thanks!

**Comment by dciancu** [comment]
Hi, Protect reporting it lacks internet means its interface names are not correctly set up, however this should not affect functionality. Failing to connect/find cameras is most likely a networking issue in regards to multicast stun traffic, sniff packets and check if they reach protect.

**Comment by Drime** [comment]
Hi @RyAndrew, I have indeed been able to make it work. Followed the steps in the readme as if I was running the container local and then changed the docker compose to the following:

```
services:
  unifi-protect:
    image: dciancu/unifi-protect-unvr-docker-arm64:stable
    [...]
    networks:
      protectvlan:
        ipv4_address: 192.168.1.60

  networks:
    protectvlan:
      name: protectvlan
      driver: ipvlan
      driver_opts:
        parent: eth0
      ipam:
        config:
          - subnet: "192.168.1.0/24"
            ip_range: "192.168.1.0/26"
            gateway: "192.168.1.1"
```

Good luck ;)
