### ISSUE TITLE
Unifi Protect can't capture the available storage

### ISSUE THREAD

**Issue by gnbon** [dciancu/unifi-protect-unvr-docker-arm64#9]
I appreciate the great work on this project. While setting it up, I encountered an issue where my storage was not recognized at all. I'm currently troubleshooting this problem. I of course changed the hostname and added boot commands as well. Either if I have the wrong settings or there are any known issues related to this, please let me know.

### Environments
- Raspberry Pi 4B(Linux raspberrypi 6.6.31)
- Using external 1TB HDD(/dev/sda1)

### df -h output
- host
```
[~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            1.6G     0  1.6G   0% /dev
tmpfs           380M  1.4M  378M   1% /run
/dev/mmcblk0p2   15G  6.8G  6.6G  51% /
tmpfs           1.9G  148K  1.9G   1% /dev/shm
tmpfs           5.0M   16K  5.0M   1% /run/lock
tmpfs           4.0M     0  4.0M   0% /sys/fs/cgroup
/dev/mmcblk0p1  510M   75M  436M  15% /boot/firmware
/dev/sda1       916G  153M  870G   1% /mnt/storage
tmpfs           380M   40K  380M   1% /run/user/1000
```

- docker
```
# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          15G  6.8G  6.6G  51% /
tmpfs            64M     0   64M   0% /dev
shm              64M   56K   64M   1% /dev/shm
tmpfs           1.9G  8.3M  1.9G   1% /run
tmpfs           1.9G  1.1M  1.9G   1% /tmp
/dev/sda1       916G  152M  870G   1% /srv
tmpfs           1.9G     0  1.9G   0% /run/lock
/dev/mmcblk0p2   15G  6.8G  6.6G  51% /etc/hosts
tmpfs           4.0M     0  4.0M   0% /sys/fs/cgroup
tmpfs           1.0G     0  1.0G   0% /var/opt/unifi-protect/tmp
```

### docker-compose.yml
```
services:
  unifi-protect:
    image: dciancu/unifi-protect-unvr-docker-arm64:stable
    tty: true
    hostname: UNVR
    extra_hosts:
      - "UNVR:127.0.1.1"
    container_name: unifi-protect
    stop_grace_period: 2m
    cgroup: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /mnt/storage/srv:/srv
      - /mnt/storage/data:/data
      - /mnt/storage/persistent:/persistent
    environment:
      - container=docker
      - STORAGE_DISK=/dev/sda1
      - TZ=UTC
    restart: unless-stopped
    cap_add:
      - dac_read_search
      - sys_admin
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/run
      - /var/run/lock
    privileged: true
    network_mode: host
```
I've also attached two screenshots showing additional information. Please let me know if you need any further details or clarification on this issue.
![image](https://github.com/user-attachments/assets/009ca383-34c4-4348-9a5e-ce8aa09fde52)
![image](https://github.com/user-attachments/assets/b39acba2-7c1a-47a8-9e5c-39879f861e42)
